export const TEMPLATES_LIST_SUCCESS = 'TEMPLATES_LIST_SUCCESS';
export const TEMPLATES_LISTBYID_SUCCESS = 'TEMPLATES_LISTBYID_SUCCESS';
export const GET_TEMPLATE_SUCCESS = 'GET_TEMPLATE_SUCCESS';
export const ADD_TEMPLATE_SUCCESS = 'ADD_TEMPLATE_SUCCESS';
export const SAVE_TEMPLATE_SUCCESS = 'SAVE_TEMPLATE_SUCCESS';
export const DELETE_TEMPLATE_SUCCESS = 'DELETE_TEMPLATE_SUCCESS';